#! /bin/bash

ROOT="$1"

cd "$ROOT"

# Do we have an old database to migrate?
if [[ -r db.sqlite ]]; then
    # get current version
    user_version=$(sqlite3 -noheader db.sqlite <<<"pragma user_version;")

    if [[ "$user_version" -eq 1 ]] ; then
        sqlite3 db.sqlite </usr/share/paste-binouse/sql/migr-1.sql
    fi
else
    # initialize database
    sqlite3 db.sqlite </usr/share/paste-binouse/sql/model.sql
fi

if ! [[ -e www ]] ; then
    ln -sf /usr/share/paste-binouse/www
fi
